name: Health Microservice Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build Image
      run: make image

    - name: Build
      run: make build

  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Lint
      run: make lint

  deploy:
    name: Publish and Deploy
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Docker Hub Login
      run: docker login -u ${{ secrets.DockerHubUsername }} -p ${{ secrets.DockerHubPassword }}

    - name: Publish
      run: make publish

