name: Health Microservice Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build Image
      run: make image

    - name: Build
      run: make build

  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Lint
      run: make lint
